# main device information
Device:
    # Name of the device on the network.
    Name: MeadowF7V2_ConfigSample


# Control how the ESP coprocessor will start and operate.
Coprocessor:
    # Should the ESP32 automatically attempt to connect to an access point at startup?
    AutomaticallyStartNetwork: 0

    # Should the ESP32 automatically reconnect to the configured access point?
    AutomaticallyReconnect: 0
    #AutomaticallyReconnect: 1
    #AutomaticallyReconnect: yes
    #AutomaticallyReconnect: no
    #AutomaticallyReconnect: true
    #AutomaticallyReconnect: false

    # Maximum number of retry attempts for connections etc. before an error code is returned.
    MaximumRetryCount: 7
    #MaximumRetryCount: 3abc
    #MaximumRetryCount:

# Network configuration.
Network:
    #
    #    Automatically attempt to get the time at startup?
    #
    GetNetworkTimeAtStartup: 1
    #
    #    Time synchronisation period in seconds.
    #
    NtpRefreshPeriod: 600
    #
    #    Name of the NTP servers.
    #
    NtpServers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        - 2.pool.ntp.org
        - 3.pool.ntp.org
    #
    #   IP addresses of the DNS servers.
    #
    DnsServers:
        - 1.1.1.1
        - 8.8.8.8
#
# Internal debug options.
#
Debug:
    #
    #   Redirect trace output to UART1 (COM1)
    #
    Uart1Use: trace
    #
    #   Set the level of information going to the trace output.
    #   Valid values: 1-4
    #
    TraceLevel: 2