{
  "Logging": {
    "LogLevel": {
      "Default": "Trace"
    }
  },
  "Lifecycle": {
    "ResetOnAppFailure": false
  },
  "Update": {
    //"UpdateServer": "192.168.1.133",
    "UpdateServer": "20.253.228.77",
    "Enabled": false
  }
}