name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Meadow.Core.Samples
      uses: actions/checkout@v3
      with:
        path: root # we have to put this in a sub-folder so we can pull Contracts/Units to a parent folder

    - name: Checkout MQTTnet fork
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/MQTTnet
        path: MQTTnet
        ref: meadow

    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging

    - name: Checkout Meadow.Foundation
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Foundation
        path: Meadow.Foundation
        ref: develop

    - name: Checkout Meadow.Core
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Core
        path: Meadow.Core
        ref: develop
        token: ${{ secrets.CI_ACCESS_TOKEN }}

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop

    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          6.0.x

    - name: Build Meadow.Core.Samples
      run: dotnet build -c Release root/source/Meadow.Core.Samples/Meadow.Core.Samples.sln

    - name: Build Meadow.Linux.Samples
      run: dotnet build -c Release root/source/Meadow.Linux.Samples/Meadow.Linux.Samples.sln
